dist: xenial
language:
  - cpp
  - python # python is only used to build docs

python:
  3.8

compiler:
  - clang
  - gcc
  
before_script:

install: 
#   - pip install --user -r requirements.txt
#   - pip install .
 - pip install --user sphinx sphinx_rtd_theme sphinxcontrib-bibtex

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target test
#   - make test
  - cd docs && make html  # build doc

before_deploy: touch build/html/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable in travis portal
  keep-history: true
  local-dir: docs/build/html
  target-branch: gh-pages
  on:
    branch:
      - master  # updates from this branch will trigger deploy
